#!/usr/bin/env php
<?php

//use DevilSwarm\AppKernel;
use DevilSwarm\Application;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

require __DIR__.'/vendor/autoload.php';

//$kernel = new AppKernel('dev', true);
//$kernel->boot();
//
//$container = $kernel->getContainer();
//$application = $container->get(Application::class);
//$application->run();

$container = new ContainerBuilder();

// Load container configuration
$loader = new YamlFileLoader($container, new FileLocator());

/** @noinspection PhpUnhandledExceptionInspection */
$loader->load(__DIR__.'/config/services.yml');

// Compile container
$container->compile();

/** @noinspection PhpUnhandledExceptionInspection */
exit($container->get(Application::class)->run());
