#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y git php php-zip
curl -sS https://getcomposer.org/installer -o composer-setup.php
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
rm composer-setup.php

git clone https://github.com/diabelb/DevilSwarm.git /tmp/devilswarm
cd /tmp/devilswarm
composer install
sudo ln -s /tmp/devilswarm/devilswarm /usr/bin/devilswarm
