services:
  _defaults:
    autowire: true

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  DevilSwarm\:
    resource: '../src/'

  DevilSwarm\Application:
    public: true
    arguments:
      - !tagged command

