# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - VERSION: "18.04"
          - VERSION: "20.04"
          - VERSION: "20.10"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test ubuntu
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Configure environment and install needed packages
        run: docker-compose build --build-arg VERSION=${{ matrix.VERSION }}

      - name: Test
        run: docker-compose run ubuntu ./devilswarm init
